[package]
name = "anchor-client"
version = "0.1.0"
authors = ["Armani Ferrante <armaniferrante@gmail.com>"]
edition = "2018"

[dependencies]
anchor-lang = { path = "../" }
solana-client = "1.5.0"
solana-sdk = "1.5.0"
thiserror = "1.0.20"